\version "2.19" 

%% Create a flagged semi-minim as in Spanish 17th-century notation, 
%% which looks like a half note with a flag.
%% Reset the notehead value to a half note; reset the flag value to an eighth
%% note; 
%% supress the warning messages that are generated by doing this.
%% 
%% USAGE: \FlagSemiMinim { d'' } OR \FlagSemiMinim { d''4 }, though any rhythmic
%% value you put will be overridden
 
FlagSemiMinim = 
#(define-music-function 
   (pitch) (ly:music?)
   "Create what looks like a half note with an eighth-note flag, suppress
   warnings not to do this."
   (ly:expect-warning (_ "adding note head to incompatible stem (type = 1/8)"))
   (ly:expect-warning (_ "maybe input should specify polyphonic voices"))
   #{
   \once \override NoteHead.duration-log = 1
   \once \override Stem.duration-log = 3
   $pitch
   #})

{ 
   \override NoteHead.style = #'mensural
   \override Flag.style = #'mensural
   \override NoteHead.font-size = #4
   \override Stem.font-size = #4
   \override Flag.font-size = #2
  \cadenzaOn
  \FlagSemiMinim { f'4 }
  \FlagSemiMinim { g'4 }
  \FlagSemiMinim { a'4 }
  \FlagSemiMinim { b'4 }
  \FlagSemiMinim { c''4 }
  \FlagSemiMinim { d''4 }
  \FlagSemiMinim { e''4 }
}

